---
title: "Stability properties for MAR(1) models"
output: pdf_document
fontsize: 10pt
geometry: margin=1.25in
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

\begin{center}
\textit{Mark Scheuerell, NOAA Northwest Fisheries Science Center, Seattle, WA USA}
\end{center}

# Background

There is growing interest in the use of first-order vector autoregressive, or VAR(1), models in ecology where they are often referred to as multivariate autoregressive, or MAR(1), models ($e.g.$, Ives $et$ $al$. 2003 $Ecological$ $Monographs$ 73:301–330).

Assume a MAR(1) model of the general form

$$
\mathbf{x}_t = \mathbf{a} + \mathbf{B} (\mathbf{x}_{t-1} - \mathbf{a}) + \mathbf{w}_t
$$

where $\mathbf{x}_t$ is an $n \times 1$ vector of state variates at time $t$, $\mathbf{a}$ is an $n \times 1$ vector of underlying levels (means) for each of the states, $\mathbf{B}$ is an $n \times n$ interaction matrix, and $\mathbf{w}_t$ is an $n \times 1$ vector of multivariate normal process errors; $\mathbf{w}_t \sim \text{MVN}(\mathbf{0}, \mathbf{Q})$.

Of particular interest here is that the variance-covariance matrix of the stationary distribution for $\mathbf{x}_t$ as $t \rightarrow \infty$ gives an indication of the relative stability of the system. 

## State-space form

This MAR(1) model can be used within a state-space framework, wherein $\mathbf{a}$ is instead included as part of a second model for the observed data $\mathbf{y}$, such that

\begin{gather*}
\mathbf{x}_t = \mathbf{B} \mathbf{x}_{t-1} + \mathbf{w}_t, \\
\mathbf{y}_t = \mathbf{x}_t + \mathbf{a} + \mathbf{v}_t,
\end{gather*}

and $\mathbf{v}_t$ is an $n \times 1$ vector of observation errors, the statistical distribution of which does not affect the variance of the stationary distribution.

# Variance of the stationary distribution

We will restrict this treatment to stationary models wherein all of the eigenvalues of $\mathbf{B}$ lie within the unit circle. Because $t = (t-1)$ as $t \rightarrow \infty$, under assumptions of stationarity we can write the process equation from the above state-space model as

$$
\mathbf{x}_t = \mathbf{B} \mathbf{x}_t + \mathbf{w}_t.
$$

From this, it follows that

$$
\rm Var(\mathbf{x}_t) = \mathbf{B} Var(\mathbf{x}_t) \mathbf{B}^\top + Var(\mathbf{w}_t).
$$

If we define $\mathbf{\Sigma} = \rm Var(\mathbf{x}_t)$, then

$$  
\mathbf{\Sigma} = \mathbf{B} \mathbf{\Sigma} \mathbf{B}^\top + \mathbf{Q}.
$$

Unfortunately, however, there is no closed-form solution for $\mathbf{\Sigma}$ when written in this form.

## The $vec$ operator

It turns out that we can use the $vec$ operator to derive an explicit solution for $\mathbf{\Sigma}$. The $vec$ operator converts an $i \times j$ matrix into an $(ij) \times 1$ column vector. For example, if

$$
\mathbf{M} = 
\begin{bmatrix}
    1 & 3 \\
    2 & 4
\end{bmatrix},
$$

then

$$
vec(\mathbf{M}) = 
\begin{bmatrix}
    1 \\
    2 \\
    3 \\
    4 
\end{bmatrix}.
$$

## Solution

Thus, if $\mathbf{I}$ is an $n \times n$ identity matrix, and we define $\mathcal{I} = (\mathbf{I} \otimes \mathbf{I})$ and $\mathcal{B} = (\mathbf{B} \otimes \mathbf{B})$, then

$$
vec(\mathbf{\Sigma}) = (\mathcal{I} - \mathcal{B})^{-1} vec(\mathbf{Q}).
$$

# Importance of species interactions to stability

Among the many ways of classifying stability, I am interested in the extent to which community interactions, relative to environmental forcing, contribute to the overall variance of the stationary distribution. In a stable system, any perturbation affecting one or more of the community members does not amplify as it moves throughout the community as a whole, such that the variances in log-densities over time would be driven almost entirely by random environmental variation. Given that same magnitude of random environmental variation, less stable systems are characterized by greater variances in the temporal dynamics of their constituents.

Here we will use determinants to measure the "volume" of a matrix. Looking back to the matrix form of the equation for the variance of the stationary distribution, we see that

$$
\mathbf{\Sigma} = \mathbf{B} \mathbf{\Sigma} \mathbf{B}^\top + \mathbf{Q}, \\
$$

and hence

$$
\mathbf{\Sigma} - \mathbf{Q} = \mathbf{B} \mathbf{\Sigma} \mathbf{B}^\top.
$$

Therefore, the volume of the difference $\mathbf{\Sigma} - \mathbf{Q}$ provides a measure of how much species interactions contribute to the variance of the stationary distribution. Taking determinants of both sides, we get

\begin{align*}
\text{det}(\mathbf{\Sigma} - \mathbf{Q}) &= \text{det}(\mathbf{B} \mathbf{\Sigma} \mathbf{B}^\top) \\
 &= \text{det}(\mathbf{B}) \text{det}(\mathbf{\Sigma}) \text{det}(\mathbf{B}^\top) \\
 &= \text{det}(\mathbf{B}) \text{det}(\mathbf{\Sigma}) \text{det}(\mathbf{B})  
\end{align*}

The proportion $\pi_\mathbf{B}$ of the volume of $\mathbf{\Sigma}$ attributable to species interactions is then

$$
\pi_\mathbf{B}  = \frac{\text{det}(\mathbf{\Sigma} - \mathbf{Q})}{\text{det}(\mathbf{\Sigma})} = \text{det}(\mathbf{B})^2.
$$

## Intra- versus inter-specific interactions

Now that we have a means for identifying the proportion $\pi_\mathbf{B}$ of the volume of $\mathbf{\Sigma}$ attributable to species interactions, we can go further and compare the relative contribution of intra- versus inter-specific interactions. To do so, we will decompose $\mathbf{B}$ into 2 matrices representing the two kinds of interactions, such that

$$
\mathbf{B} = \mathbf{\Delta} + \mathbf{\Omega}.
$$

The matrix $\mathbf{\Delta}$ has density-dependent effects for each community member along the diagonal and zeroes elsewhere. The matrix $\mathbf{\Omega}$ contains zeroes along the diagonal and (potentially) non-zero entries in the off-diagonals. 

We can again use determinants to measure the relative contributions of intra- $(\mathbf{\Delta})$ versus inter-specific $(\mathbf{\Omega})$ interactions to the volume of $\mathbf{B}$, where

\begin{align*}
\text{det}(\mathbf{B}) &= \text{det}(\mathbf{\Delta} + \mathbf{\Omega}) \\
  &= \text{det}(\mathbf{\Delta}) \text{det}(\mathbf{I} + \mathbf{\Omega} \mathbf{\Delta}^{-1}).
\end{align*}

Therefore, the proportion $\pi_\mathbf{\Delta}$ of the volume of $\mathbf{B}$ attributable to density-dependent interactions is then

$$
\pi_\mathbf{\Delta}  = \frac{\text{det}(\mathbf{\Delta})}{\text{det}(\mathbf{B})} = \text{det}(\mathbf{I} + \mathbf{\Omega} \mathbf{\Delta}^{-1})^{-1},
$$

where $\mathbf{I}$ is again an $n \times n$ identity matrix. The proportion of the volume of $\mathbf{B}$ attributable to competition, predator-prey interactions, etc is then simply $\pi_\mathbf{\Omega} = 1 - \pi_\mathbf{\Delta}$.
