---
title: "Compact forms for MARSS models with covariates"
output: pdf_document
fontsize: 10pt
geometry: margin=1.25in
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

\begin{center}
\textbf{Mark D. Scheuerell} \\
\text{Northwest Fisheries Science Center} \\
\text{National Oceanic and Atmospheric Administration} \\
\text{Seattle, WA USA} \\
\text{mark.scheuerell@noaa.gov}
\end{center}

# Standard MARSS model

There is growing interest in the use of first-order vector autoregressive, or VAR(1), models in ecology where they are often referred to as multivariate autoregressive, or MAR(1), models ($e.g.$, Ives $et \ al$. 2003 $Ecol \ Monographs$ 73:301–330). 

## Process equation

The underlying process in a MAR(1) model is a discrete time version of a multivariate Gompterz equation for $n$ "species", which is typically written as

$$
\mathbf{x}_t = \mathbf{B} \mathbf{x}_{t-1} + \mathbf{w}_t,
$$

where $\mathbf{x}_t$ is an $n \times 1$ vector of state variates at time $t$, $\mathbf{B}$ is an $n \times n$ matrix of interaction strengths, and $\mathbf{w}_t$ is an $n \times 1$ vector of multivariate normal process errors; $\mathbf{w}_t \sim \text{MVN}(\mathbf{0}, \mathbf{Q})$.

Often we would like to include the effects of some number $p$ of external drivers of the system, whether they be environmental ($e.g.$, temperature) or anthropogenic ($i.e.$, harvest). In those cases, the model is expanded to

$$
\mathbf{x}_t = \mathbf{B} \mathbf{x}_{t-1} + \mathbf{C} \mathbf{c}_{t-h} + \mathbf{w}_t,
$$
where $\mathbf{C}$ is an $n \times p$ matrix of covariate effects, and $\mathbf{c}_t$ is a $p \times 1$ vector of covariates at time $t-h$ where $0 \leq h < T$.

## Observation equation

This process model can be used within a state-space framework wherein we add a second model for the observed data $\mathbf{y}$, such that

\begin{gather*}
\mathbf{x}_t = \mathbf{B} \mathbf{x}_{t-1} + \mathbf{C} \mathbf{c}_{t-h} + \mathbf{w}_t, \\
\mathbf{y}_t = \mathbf{x}_t + \mathbf{a} + \mathbf{v}_t,
\end{gather*}

$\mathbf{a}$ is an $n \times 1$ vector of offsets, and $\mathbf{v}_t$ is an $n \times 1$ vector of observation errors; $\mathbf{v}_t \sim \text{MVN}(\mathbf{0}, \mathbf{R})$.

# Compact MARSS model: Option 1

## Process equation

The above MARSS model can be rewritten in a more compact form, if we make some assumptions about the time lag $h$ for the covariates. Beginning with the process equation, if $h = 1$ and all of the covariates have been scaled to have zero mean and unit variance, then we can redefine the MAR(1) model as

$$
\mathbf{x}_t^* = \mathbf{B}^* \mathbf{x}_{t-1}^* + \mathbf{w}_t^* ~ \text{with} ~ \mathbf{w}_t^* \sim \text{MVN}(\mathbf{0}, \mathbf{Q}^*),
$$

with the following definitions:

$$
\mathbf{x}_t^* = 
\begin{bmatrix}
    \mathbf{x}_t \\
    \mathbf{c}_t
\end{bmatrix},
$$

$$
\mathbf{B}^* = 
\begin{bmatrix}
    \mathbf{B} & \mathbf{C}\\
    \mathbf{0} & \mathbf{0}
\end{bmatrix}, ~ \text{and}
$$

$$
\mathbf{Q}^* = 
\begin{bmatrix}
    \mathbf{Q} & \mathbf{0}\\
    \mathbf{0} & \mathbf{I}_p
\end{bmatrix}. 
$$

Here $\mathbf{I}_p$ is a $p \times p$ identity matrix. Thus, these vectors and matrices will have new dimensions, such that $\mathbf{x}_t^*$ is $(n + p) \times 1$, $\mathbf{B}_t^*$ is $(n + p) \times (n + p)$, and $\mathbf{Q}_t^*$ is also $(n + p) \times (n + p)$.

## Observation equation

The observation equation is then rewritten as

$$
\mathbf{y}_t^* = \mathbf{x}_t^* + \mathbf{v}_t^* ~ \text{with} ~ \mathbf{v}_t^* \sim \text{MVN}(\mathbf{0}, \mathbf{R}^*),
$$

and

$$
\mathbf{y}_t^* = 
\begin{bmatrix}
    \mathbf{y}_t \\
    \mathbf{c}_t
\end{bmatrix} ~ \text{and}
$$

$$
\mathbf{R}^* = 
\begin{bmatrix}
    \mathbf{R} & \mathbf{0}\\
    \mathbf{0} & \mathbf{0}
\end{bmatrix}. 
$$

These new vectors and matrices will have dimensions where $\mathbf{y}_t^*$ is $(n + p) \times 1$ and $\mathbf{Q}_t^*$ is $(n + p) \times (n + p)$.

# Compact MARSS model: Option 2

If the covariates have not been scaled, then the state-space model must instead be written as

\begin{gather*}
\mathbf{x}_t^* = \mathbf{B}^* \mathbf{x}_{t-1}^* + \mathbf{w}_t^* ~ \text{with} ~ \mathbf{w}_t^* \sim \text{MVN}(\mathbf{0}, \mathbf{Q}^*) \\
\mathbf{y}_t^* = \mathbf{x}_t^* + \mathbf{a}^* + \mathbf{v}_t^* ~ \text{with} ~ \mathbf{v}_t^* \sim \text{MVN}(\mathbf{0}, \mathbf{R}^*),
\end{gather*}

wherein 

$$
\mathbf{Q}^* = 
\begin{bmatrix}
    \mathbf{Q} & \mathbf{0}\\
    \mathbf{0} & \mathbf{S}
\end{bmatrix}, ~ \text{and} 
$$

$$
\mathbf{S} = 
\begin{bmatrix}
    \text{Var}(c_1) & 0 & 0 \\
    0 & \ddots & 0 \\
    0 & 0 & \text{Var}(c_p)
\end{bmatrix}. 
$$

The $p \times p$ matrix $\mathbf{S}$ contains the variances of each of the $p$ covariates along the diagonal and 0’s elsewhere ($i.e.$, they are input and not estimated). To allow for non-zero means in the covariates, an $n \times 1$ vector $\mathbf{a}$  containing covariate means must be included in $\mathbf{a}^*$ , such that

$$
\mathbf{a}^* = 
\begin{bmatrix}
    \mathbf{0} \\
    \mathbf{a}
\end{bmatrix}.
$$
